apiVersion: v1
kind: Namespace
metadata:
  name: polenta

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: polenta-ingress
  namespace: polenta
spec:
  ingressClassName: cloudflare-tunnel
  rules:
    - host: polentasardinedeploy.marcobacis.com
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: polenta-svc
                port:
                  number: 80

---

apiVersion: v1
kind: Service
metadata:
  name: polenta-api-svc
  namespace: polenta
spec:
  ports:
  - port: 80
    name: web
  selector:
    app: polenta

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: polenta-api
  namespace: polenta
spec:
  selector:
    matchLabels:
      app: polenta
  replicas: 1
  template:
    metadata:
      labels:
        app: polenta
    spec:
      containers:
      - name: polenta
        image: ghcr.io/marcobacis/polenta-sardine-deploy:develop
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: web